export enum ProviderTxStatus {
  INITIATED = 'INITIATED',
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
}

export enum ProviderEventStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
  DEAD_LETTER = 'DEAD_LETTER',
}

export enum OutboxStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PUBLISHED = 'PUBLISHED',
  FAILED = 'FAILED',
  DEAD_LETTER = 'DEAD_LETTER',
}

export enum StatementImportStatus {
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum ReconciliationStatus {
  DISCOVERED = 'DISCOVERED',
  MATCHING = 'MATCHING',
  MATCHED = 'MATCHED',
  EXCEPTION = 'EXCEPTION',
  RESOLVED = 'RESOLVED',
}

export enum ReconciliationException {
  AMOUNT_MISMATCH = 'AMOUNT_MISMATCH',
  MISSING_INTERNAL_TRANSACTION = 'MISSING_INTERNAL_TRANSACTION',
  MISSING_PROVIDER_TRANSACTION = 'MISSING_PROVIDER_TRANSACTION',
  STATUS_MISMATCH = 'STATUS_MISMATCH',
  UNEXPECTED_FEE = 'UNEXPECTED_FEE',
}
